StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60FC2921768CE182}" {
   Id "CSI-Name"
   Target_en_us "Coaltion Squad Interface"
   Target_de_de "Coaltion Squad Interface"
   Modified 1627138834
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60FC292127199A67}" {
   Id "CSI-Player_Selection-Color_Team_Open_Menu_Keybind_Text"
   Target_en_us "Open Player Selection / Color Team Menus"
   Target_de_de "Spielerauswahl / Teamfarben Menüs"
   Modified 1627138825
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60FC29219E95EC3B}" {
   Id "CSI-Player_Selection_Open_Menu"
   Target_en_us "Open Player Selection Menu"
   Target_de_de "Spielerauswahl öffnen"
   Modified 1627138801
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60FC29218EC368AD}" {
   Id "CSI-Settings_Open_Menu"
   Target_en_us "Open CSI Settings Menu"
   Target_de_de "CSI Einstellungen öffnen"
   Modified 1627138788
   Author "pi123"
   LastChanged "pi123"
  }
 }
}