StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60FC2AB4E3AB1680}" {
   Id "CSI-Ingame_Settings_Compass_Settings_Subtitle"
   Target_en_us "// Compass Settings"
   Target_fr_fr "// Paramètres de la boussole"
   Target_de_de "// Kompass Einstellungen"
   Modified 1635697014
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB51F7A4396}" {
   Id "CSI-Ingame_Settings_Compass_Visible_Toggle"
   Target_en_us "Compass Visible"
   Target_fr_fr "Boussole visible"
   Target_de_de "Kompass Sichtbar"
   Modified 1635697036
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB52F2BC348}" {
   Id "CSI-Ingame_Settings_CT_Menu_Toggle"
   Target_en_us "Personal CT Menu"
   Target_fr_fr "Menu CT personnel"
   Target_de_de "Persönliches CT Menü"
   Modified 1635697054
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB4F9541A4A}" {
   Id "CSI-Ingame_Settings_Group_Display_Settings_Subtitle"
   Target_en_us "// Group Display Settings"
   Target_fr_fr "// Paramètres d'affichage du groupe"
   Target_de_de "// Gruppenansicht Einstellungen"
   Modified 1635697074
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB50F3EBDCE}" {
   Id "CSI-Ingame_Settings_Group_Display_Toggle"
   Target_en_us "Group Display Visible"
   Target_fr_fr "Affichage de groupe visible"
   Target_de_de "Gruppenansicht Sichtbar"
   Modified 1635698906
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{617D3179DFC2ACF5}" {
   Id "CSI-Ingame_Settings_Group_In_Nametags_Selector"
   Target_en_us "Group In Nametags"
   Target_fr_fr "Groupe In Etiquettes de nom"
   Target_de_de "Gruppe in Spielernamen"
   Modified 1635699342
   Author "Njpatman"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB515847576}" {
   Id "CSI-Ingame_Settings_Icon_Scale_Selector"
   Target_en_us "Icon Scale"
   Target_fr_fr "Icon Scale"
   Target_de_de "Bild Größe"
   Modified 1635698915
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB4F1665E93}" {
   Id "CSI-Ingame_Settings_Nametag_Settings_Subtitle"
   Target_en_us "// Nametag Settings"
   Target_fr_fr "// Paramètres des noms"
   Target_de_de "// Spielernamen Einstellungen"
   Modified 1635699063
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB530152B34}" {
   Id "CSI-Ingame_Settings_Nametags_Position_Selector"
   Target_en_us "Nametags Position"
   Target_fr_fr "Position des noms"
   Target_de_de "Spielername Position"
   Modified 1635698935
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB53455A054}" {
   Id "CSI-Ingame_Settings_Nametags_Range_Selector"
   Target_en_us "Nametags Range"
   Target_fr_fr "Distance d'affichage des noms"
   Target_de_de "Spielername Distanz"
   Modified 1635698953
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB53E976773}" {
   Id "CSI-Ingame_Settings_Nametags_Role_Toggle"
   Target_en_us "Role In Nametags"
   Target_fr_fr "Afficher le rôle avec le nom"
   Target_de_de "Rolle bei Spielername"
   Modified 1635699024
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB526BE94B7}" {
   Id "CSI-Ingame_Settings_Nametags_Toggle"
   Target_en_us "Nametags Visible"
   Target_fr_fr "Affichage des noms"
   Target_de_de "Spielername Sichtbar"
   Modified 1635699029
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{617D3179CE313152}" {
   Id "CSI-Ingame_Settings_Nametags_Use_LOS_Selector"
   Target_en_us "Nametags Use LOS"
   Target_fr_fr "Porte-noms Utiliser LOS"
   Target_de_de "Spielernamen benutzen LOS"
   Modified 1635699358
   Author "Njpatman"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB504482503}" {
   Id "CSI-Ingame_Settings_Personal_Icon_Toggle"
   Target_en_us "Personal Icon Visible"
   Target_fr_fr "Icône personnelle visible"
   Target_de_de "Persönliches Bild Sichtbar"
   Modified 1635699038
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB5542D52A5}" {
   Id "CSI-Ingame_Settings_Rank_Visible_Toggle"
   Target_en_us "Rank Visible"
   Target_fr_fr "Rang visible"
   Target_de_de "Rang Sichtbar"
   Modified 1635699043
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB4E732B26F}" {
   Id "CSI-Ingame_Settings_Squad_Radar_Settings_Subtitle"
   Target_en_us "// Squad Radar Settings"
   Target_fr_fr "// Paramètres du radar d'escouade"
   Target_de_de "// Team Radar Einstellungen"
   Modified 1635699058
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB503976972}" {
   Id "CSI-Ingame_Settings_Squad_Radar_Toggle"
   Target_en_us "Squad Radar Visible"
   Target_fr_fr "Radar d'escouade visible"
   Target_de_de "Team Radar Sichtbar"
   Modified 1635699080
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB5537D6748}" {
   Id "CSI-Ingame_Settings_Stamina_Bar_Toggle"
   Target_en_us "Stamina Bar Visible"
   Target_fr_fr "Barre d'endurance visible"
   Target_de_de "Ausdauerleiste Sichtbar"
   Modified 1635699090
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB55E5B68E9}" {
   Id "CSI-Ingame_Settings_Subtitle"
   Target_en_us "// General Settings"
   Target_fr_fr "// Réglages généraux"
   Target_de_de "// Allgemeine Einstellungen"
   Modified 1635699098
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB55AAA58CE}" {
   Id "CSI-Ingame_Settings_Title"
   Target_en_us "CSI Settings"
   Target_fr_fr "Réglages CSI"
   Target_de_de "CSI Einstellungen"
   Modified 1635699106
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2921768CE182}" {
   Id "CSI-Name"
   Target_en_us "Coaltion Squad Interface"
   Target_fr_fr "Coaltion Squad Interface"
   Target_de_de "Coaltion Squad Interface"
   Modified 1635699111
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC292127199A67}" {
   Id "CSI-Player_Selection-Color_Team_Open_Menu_Keybind_Text"
   Target_en_us "Open Player Selection / Color Team Menus"
   Target_fr_fr "Ouvrir la sélection des joueurs / Menu des couleurs"
   Target_de_de "Spielerauswahl / Teamfarben Menüs"
   Modified 1635699119
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC29219E95EC3B}" {
   Id "CSI-Player_Selection_Open_Menu"
   Target_en_us "Open Player Selection Menu"
   Target_fr_fr "Ouvrir le menu de sélection des joueurs"
   Target_de_de "Spielerauswahl öffnen"
   Modified 1635699127
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB6019F0012}" {
   Id "CSI-Player_Selection_Subtitle"
   Target_en_us "// Select A Player To Edit"
   Target_fr_fr "// Sélectionnez un joueur à modifier"
   Target_de_de "// Wähle einen Spieler zum bearbeiten aus"
   Modified 1635699140
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB60262EFE6}" {
   Id "CSI-Player_Selection_Title"
   Target_en_us "Player Selection"
   Target_fr_fr "Sélection des joueurs"
   Target_de_de "Spielerauswahl"
   Modified 1635699147
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB5820FFFAA}" {
   Id "CSI-Player_Settings_Color_Teams_Set_Subtitle"
   Target_en_us "// Set Color Team"
   Target_fr_fr "// Définir la couleur de l'équipe"
   Target_de_de "// Farbteam auswählen"
   Modified 1635699162
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB5D307EB14}" {
   Id "CSI-Player_Settings_No_Player_Selected"
   Target_en_us "No Player Selected"
   Target_fr_fr "Aucun joueur sélectionné"
   Target_de_de "Kein Spieler ausgewählt"
   Modified 1635699167
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB5B05AC05E}" {
   Id "CSI-Player_Settings_Override_Icon_Subtitle"
   Target_en_us "// Override Icon"
   Target_fr_fr "// Icône de remplacement"
   Target_de_de "// Bild überschreiben"
   Modified 1635699178
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC2AB5DA873B5D}" {
   Id "CSI-Player_Settings_Title"
   Target_en_us "Player Settings"
   Target_fr_fr "Paramètres du joueur"
   Target_de_de "Spieler Einstellungen"
   Modified 1635699186
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60FC29218EC368AD}" {
   Id "CSI-Settings_Open_Menu"
   Target_en_us "Open CSI Settings Menu"
   Target_fr_fr "Ouvrir le menu Paramètres CSI"
   Target_de_de "CSI Einstellungen öffnen"
   Modified 1635699191
   Author "pi123"
   LastChanged "Njpatman"
  }
 }
}