SystemSettings : "{86E953538A28A98D}Configs/Systems/ChimeraSystemsConfig.conf" {
 Systems {
  CSI_ClientSystem "{68D07A32A6604C5B}" {
   SystemLocation Client
  }
  CSI_HUDSystem "{68D07A32A7EAF372}" {
   SystemLocation Client
   SystemPoints 0x4 0x10
  }
  CSI_PlayerDisconnectSystem "{68D07A32A25157A8}" {
   SystemLocation Server
  }
 }
}