SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  CSI_ClientSystem "{697A3686AFAD6422}" {
  }
  CSI_HUDSystem "{697A3686A868A015}" {
  }
  CSI_PlayerDisconnectSystem "{697A3686A962521F}" {
  }
 }
}