MenuManager {
 MenuPresets {
  MenuPreset CSI_PlayerSettingsMenu {
   Layout "{2D837E6845C3D7D8}UI/Layouts/Menus/PlayerSettings/CSI_PlayerSettingsMenu.layout"
   Class "CSI_PlayerSettingsMenu"
  }
 }
}