ActionManager {
 Actions {
  Action CSI_PlayerSettingsMenu {
   InputSource InputSourceSum "{608CDAA32815126C}" {
    Sources {
     InputSourceSum "{609358FD4B0C584E}" {
      Sources {
       InputSourceValue "{609358FD72BFEC30}" {
        FilterPreset "click"
        Input "keyboard:KC_HOME"
        Filter InputFilterClick "{61E73039AB6D5573}" {
        }
       }
      }
     }
     InputSourceCombo "{609358F3C61FC164}" {
      FilterPreset "gamepad:click"
      Sources {
       InputSourceValue "{609358F3CD93073D}" {
        Input "gamepad0:menu"
       }
       InputSourceValue "{609358F3CE5B7BE1}" {
        Input "gamepad0:pad_left"
        Filter InputFilterDown "{609358FDF04045E2}" {
        }
       }
      }
     }
    }
   }
  }
  Action RevealCSIUI {
   Transition CurveCubicSplineFloat "{66CA2A78F9B7DFF7}" {
    SplineType ModifiedAkima
    EndCondition OpenFlat
    Knots {
     0
    }
    ParamMin 0
    ParamMax 1
    ValueMin 0
    ValueMax 1
    UnrestrictedFlags 0
    Values {
     0
    }
   }
   InputSource InputSourceSum "{608CDAA34F5973B2}" {
    Sources {
     InputSourceSum "{609358FD4B0C584E}" {
      Sources {
       InputSourceValue "{609358FD72BFEC30}" {
        FilterPreset "click"
        Input "keyboard:KC_INSERT"
        Filter InputFilterPressed "{62024A93870213DA}" {
        }
       }
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext IngameContext {
   ActionRefs +{
    "CSI_PlayerSettingsMenu"
    "RevealCSIUI"
   }
  }
 }
}