MenuManager {
 MenuPresets {
  MenuPreset CSI_PlayerSettingsDialog {
   Layout "{CDAE569CD2A70854}UI/layouts/Menus/Dialogs/CSI_PlayerSettingsDialog.layout"
   Class "CSI_PlayerSettingsDialog"
  }
 }
}