SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{66C6726CA82C65A3}" {
  Name "CSI Settings"
  Description "Coalition Squad Interface Settings"
  Icon "{22581B54C987F973}UI/Textures/Editor/Attributes/FreeRoamBuilding/Single_objects_Tab-32.edds"
 }
 m_iPriority 5
 m_bIsGlobalAttributeCategory 1
}